Repository PHPCompatibility/PHPCompatibilityWP, pull requests merged in 2024-04, with the labels that each got.

#57 GH Actions: work around intermittent apt-get errors
  .github/workflows/ci.yml
Labels: chores/QA

#56 Composer: avoid writing a lock file
  composer.json
Labels: chores/QA

#55 WP 6.5: account for new function polyfills
  PHPCompatibilityWP/ruleset.xml
  Test/WPTest.php
Labels: enhancement

#58 Changelog for the release of version 2.1.5
  README.md
Labels: PR: ready for review, documentation, meta
